require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# target 'App' configuration
target 'App' do
  capacitor_pods
  # Add your Pods here
end
